name: MTS Bank test

env:
  OS: ubuntu-latest
  
on: push

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Selenoid setup"
        run: curl -s https://aerokube.com/cm/bash  | bash
        
      - name: "access rights"
        run: chmod +x ./cm
        
      - name: "Selenoid start"
        run: ./cm selenoid start --vnc
        
      - name: "Selenoid ui"
        run: ./cm selenoid-ui start
        
      - name: "push"
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
        
      - name: "run tests"
        if: always()
        run: mvn clean test
        continue-on-error: true
        
      - name: "allure report"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: allure-history
          
      - name: "push allure"
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.CHUBZZZ_SECRET_EXAMS }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
